### ISSUE TITLE
Autocompletions don't work (log provided)

### ISSUE THREAD

**Issue by yandodov** [bradlc/sublime-tailwindcss#4]
I just installed the plugin via Package Control and added the Node path in my Sublime preferences file. However, while I write `@apply` in a CSS file, I get no autocomplete suggestions and the following error appears in the Sublime console:

```
reloading plugin TailwindCSSAutocomplete.TailwindCSSAutocomplete
reloading plugin Xdebug Client.main
plugins loaded
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Sublime Text 3\Installed Packages\TailwindCSSAutocomplete.sublime-package\TailwindCSSAutocomplete.py", line 32, in get_completions
    path = output.decode('utf-8').splitlines()[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 249, in synthesize_on_activated_async
    el.on_activated_async(v)
  File "C:\Users\USER\AppData\Roaming\Sublime Text 3\Installed Packages\TailwindCSSAutocomplete.sublime-package\TailwindCSSAutocomplete.py", line 110, in on_activated_async
    self.get_completions(view, folder)
  File "C:\Users\USER\AppData\Roaming\Sublime Text 3\Installed Packages\TailwindCSSAutocomplete.sublime-package\TailwindCSSAutocomplete.py", line 42, in get_completions
    except TimeoutExpired:
NameError: global name 'TimeoutExpired' is not defined
Package Control: Skipping automatic upgrade, last run at 2019-03-22 16:02:35, next run at 2019-03-22 17:02:35 or after
```

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 688, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Users\USER\AppData\Roaming\Sublime Text 3\Installed Packages\TailwindCSSAutocomplete.sublime-package\TailwindCSSAutocomplete.py", line 126, in on_query_completions
    items = self.instances[folder]['items']
KeyError: 'items'
```

**Comment by jago86** [comment]
I'm facing the same issue in Sublime Text 3.2.1, MacOs Mojave, Python 2.7.10. There is any solution?

**Comment by r-moore** [comment]
Same issue here on MacOS Mojave, ST 3.2.1, Python 2.7.10 (default) and Python 3.7.4 (python3):

```
Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Sublime Text 3/Installed Packages/TailwindCSSAutocomplete.sublime-package/TailwindCSSAutocomplete.py", line 29, in get_completions
    shell = sublime.platform() == 'windows'
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1370, in _execute_child
  File "./python3.3/os.py", line 791, in fsencode
TypeError: expect bytes or str, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 249, in synthesize_on_activated_async
    el.on_activated_async(v)
  File "/Users/USER/Library/Application Support/Sublime Text 3/Installed Packages/TailwindCSSAutocomplete.sublime-package/TailwindCSSAutocomplete.py", line 110, in on_activated_async
    self.get_completions(view, folder)
  File "/Users/USER/Library/Application Support/Sublime Text 3/Installed Packages/TailwindCSSAutocomplete.sublime-package/TailwindCSSAutocomplete.py", line 42, in get_completions
    except TimeoutExpired:
NameError: global name 'TimeoutExpired' is not defined
```

**Comment by arrcorona** [comment]
any update on this?

**Comment by james2doyle** [comment]
Try my fork: https://github.com/james2doyle/sublime-tailwindcss

It has added logging features and fixes and issue with cloning vs. package control

I have had 3 PRs open since March and they haven't been addressed so maybe give this a shot and see if it fixes your issues.
