### ISSUE TITLE
Getting exceptions in post save and query completions hook

### ISSUE THREAD

**Issue by lokesh1729** [bradlc/sublime-tailwindcss#5]
```python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 576, in on_post_save_async
    callback.on_post_save_async(v)
  File "/Users/slokesh/Library/Application Support/Sublime Text 3/Installed Packages/TailwindCSSAutocomplete.sublime-package/TailwindCSSAutocomplete.py", line 115, in on_post_save_async
    if view.file_name() == self.instances[folder]['config_file']:
KeyError: 'config_file'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 688, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/Users/slokesh/Library/Application Support/Sublime Text 3/Installed Packages/TailwindCSSAutocomplete.sublime-package/TailwindCSSAutocomplete.py", line 126, in on_query_completions
    items = self.instances[folder]['items']
KeyError: 'items'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 688, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/Users/slokesh/Library/Application Support/Sublime Text 3/Installed Packages/TailwindCSSAutocomplete.sublime-package/TailwindCSSAutocomplete.py", line 126, in on_query_completions
    items = self.instances[folder]['items']
KeyError: 'items'
```

**Comment by james2doyle** [comment]
Try my fork: https://github.com/james2doyle/sublime-tailwindcss

This issue should be fixed and has extra logging as well

I have had 3 PRs open since March and they haven't been addressed so maybe give this a shot and see if it fixes your issues
