### ISSUE TITLE
Error: KeyError: 'config_file'

### ISSUE THREAD

**Issue by james2doyle** [bradlc/sublime-tailwindcss#6]
*Sublime Build 3210*

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 576, in on_post_save_async
    callback.on_post_save_async(v)
  File "/Users/jamesdoyle/Library/Application Support/Sublime Text 3/Installed Packages/TailwindCSSAutocomplete.sublime-package/TailwindCSSAutocomplete.py", line 115, in on_post_save_async
    if view.file_name() == self.instances[folder]['config_file']:
KeyError: 'config_file'
```

**Comment by james2doyle** [comment]
@bradlc any update on this?

**Comment by james2doyle** [comment]
@bradlc any update on this?
